version: "3"

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: "backend"
  #   restart: always
  #   tty: true
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo

  mongo:
    image: mongo
    container_name: "mongo"
    volumes:
      - ./mongodata:/data/db
    ports:
      - "27017:27017"
